superlists/accounts/urls.py
# /accounts/urls.py

from django.conf.urls import patterns, url
from django.contrib.auth.views import logout
from . import views as accounts_views

app_name = 'accounts'

urlpatterns = [
    url(r'^login$', accounts_views.persona_login, name='persona_login'),
    url(r'^logout$', logout, {'next_page': '/'}, name='logout'),
]

superlists/lists/urls.py
# /lists/urls.py

from django.conf.urls import patterns, url
from . import views as lists_views

app_name = 'lists'

urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/$', lists_views.view_list, name='view_list'),
    url(r'^new$', lists_views.new_list, name='new_list'),
    url(r'^users/(.+)/$', lists_views.my_lists, name='my_lists'),
    url(r'^(?P<pk>[0-9]+)/share$', lists_views.share_list, name='share_list'),
]

superlists/superlists/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from lists import views as lists_views
from lists.urls import urlpatterns as lists_urls
from accounts.urls import urlpatterns as accounts_urls


urlpatterns = [
    url(r'^$', lists_views.home_page, name='home'),
    url(r'^lists/', include(lists_urls, namespace='lists')),
    url(r'^accounts/', include(accounts_urls, namespace='accounts')),

    url(r'^admin/', admin.site.urls),
]

superlists/accounts/models.py
# /accounts/models.py

from django.db import models
from django.utils import timezone


class User(models.Model):
    email = models.EmailField(primary_key=True)
    last_login = models.DateTimeField(default=timezone.now)
    REQUIRED_FIELDS = ()
    USERNAME_FIELD = 'email'

    def is_authenticated(self):
        return True

superlists/lists/models.py
# /lists/models.py

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models


class List(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    shared_with = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='shared_lists'
    )

    def get_absolute_url(self):
        return reverse('lists:view_list', args=[self.id])

    @property
    def name(self):
        return self.item_set.first().text

    def __str__(self):
        return '{}번째 리스트'.format(self.pk)


class Item(models.Model):
    text = models.TextField(default='', unique=False)
    list = models.ForeignKey(List, default=None)

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

    def __str__(self):
        return self.text

superlists/lists/forms.py
from django import forms
from django.core.exceptions import ValidationError

from lists.models import Item


EMPTY_LIST_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "이미 리스트에 해당 아이템이 있습니다"

class ItemForm(forms.models.ModelForm):

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
            'placeholder': '작업 아이템 입력',
            'class': 'form-control input-lg',
            }),
        }
        error_messages = {
            'text': {'required': EMPTY_LIST_ERROR}
        }

    def save(self, for_list):
        self.instance.list = for_list
        return super().save()


class ExistingListItemForm(ItemForm):
    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

    def save(self):
        return forms.models.ModelForm.save(self)

superlists/accounts/views.py
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.http import HttpResponse


def persona_login(request):
    user = authenticate(assertion=request.POST['assertion'])
    if user:
        login(request, user)
    return HttpResponse('OK')

superlists/lists/views.py
# /lists/views.py

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.shortcuts import redirect
from django.shortcuts import render

from lists.forms import ExistingListItemForm
from lists.forms import ItemForm
# from lists.forms import NewListForm
from lists.models import List


User = get_user_model()

def home_page(request):
    return render(request, 'home.html', {'form': ItemForm()})

def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        list_ = List()
        if request.user.is_authenticated():
            list_.owner = request.user
        list_.save()
        form.save(for_list=list_)
        return redirect(list_)
    else:
        return render(request, 'home.html', {"form": form})

def view_list(request, pk):
    list_ = List.objects.get(id=pk)
    form = ExistingListItemForm(for_list=list_)
    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(request, 'list.html', {'list': list_, "form": form})

def my_lists(request, email):
    owner = User.objects.get(email=email)
    return render(request, 'my_lists.html', {'owner': owner})

def share_list(request, pk):
    list_ = List.objects.get(id=pk)
    list_.shared_with.add(request.POST['email'])
    return redirect(list_)

superlists/lists/templates/base.html
<!DOCTYPE html>

<html lang="ko">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>To-Do lists</title>
        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <link href="/static/base.css" rel="stylesheet" media="screen">
    </head>

    <body>
    <div class="container">

        <nav class="navbar navbar-default" role="navigation">
            <a class="navbar-brand" href="/">Superlists</a>
            {% if user.email %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'lists:my_lists' user.email %}">나의 목록</a></li>
                </ul>
                <a class="btn navbar-btn navbar-right" id="id_logout" href="{% url 'accounts:logout' %}">로그아웃&emsp;</a>
                <span class="navbar-text navbar-right">로그인됨 {{ user.email }}</span>
            {% else %}
                <a class="btn navbar-btn navbar-right" id="id_login" href="#">로그인&emsp;</a>
            {% endif %}
        </nav>

        <div class="row">
            <div class="col-md-6 col-md-offset-3 jumbotron">
                <div class="text-center">
                    <h1>{% block header_text %}{% endblock %}</h1>

                    {% block list_form %}
                    <form method="POST" action="{% block form_action %}{% endblock %}">
                        {{ form.text }}
                        {% csrf_token %}
                        {% if form.errors %}
                            <div class="form-group has-error">
                                <div class="help-block">{{ form.text.errors }}</div>
                            </div>
                        {% endif %}
                    </form>
                    {% endblock %}

                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                {% block table %}
                {% endblock %}
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                {% block extra_content %}
                {% endblock %}
            </div>
        </div>

    </div>
    <script src="http://code.jquery.com/jquery.min.js"></script>
    <script src="https://login.persona.org/include.js"></script>
    <script src="/static/accounts.js"></script>
    <script src="/static/list.js"></script>
    <script>
    /* global $, Superlists, navigator */
    $(document).ready(function () {
        var user = "{{ user.email }}" || null;
        var token = "{{ csrf_token }}";
        var urls = {
            login: "{% url 'accounts:persona_login' %}",
            logout: "TODO",
        };
        Superlists.Accounts.initialize(navigator, user, token, urls);
    });
    </script>
    </body>
</html>

superlists/lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new <br> To-Do list{% endblock %}

{% block form_action %}{% url 'lists:new_list' %}{% endblock %}

superlists/lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}{% url 'lists:view_list' list.id %}{% endblock %}

{% block table %}
    <table id="id_list_table" class="table">
        {% for item in list.item_set.all %}
            <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
        {% endfor %}
    </table>

    {% if list.owner %}
        <p>List owner: <span id="id_list_owner">{{ list.owner.email }}</span><p>
    {% endif %}

{% endblock %}

{% block extra_content %}
<div class="row">

    <div class="col-md-6">
        <h3>Shared with</h3>
        <ul>
            {% for share in list.shared_with.all %}
                <li class="list-share">{{ share.email }}</li>
            {% endfor %}
        </ul>
    </div>

    <div class="col-md-4 col-md-offset-1">
        <h3>Share this list:</h3>
        <form class="form-inline" method="POST" action="{% url 'lists:share_list' list.id %}">
            {% csrf_token %}
            <input name="email" placeholder="your-friend@example.com"/>
        </form>
    </div>

</div>
{% endblock %}

superlists/lists/templates/my_lists.html
{% extends 'base.html' %}

{% block header_text %}나의 목록{% endblock %}

{% block list_form %}{% endblock %}

{% block extra_content %}

    <h2>{{ owner.email }}'s lists</h2>
    <ul>
        {% for list in owner.list_set.all %}
            <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
        {% endfor %}
    </ul>

    <h2>Lists shared by other users</h2>
    <ul>
    {% for list in owner.shared_lists.all %}
        <li>
            <a href="{{ list.get_absolute_url }}">{{ list.name }}</a>
            ({{ list.owner.email }})
        </li>
    {% endfor %}
    </ul>

{% endblock %}